//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPATools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPATools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IfModule mod_mime.c&gt;
        ///    AddType text/xml .plist
        ///    AddType application/x-apple-aspen-config .mobileconfig
        ///&lt;/IfModule&gt;.
        /// </summary>
        internal static string htaccess {
            get {
                return ResourceManager.GetString("htaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagefail {
            get {
                object obj = ResourceManager.GetObject("imagefail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imageok {
            get {
                object obj = ResourceManager.GetObject("imageok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///        &lt;title&gt;[[BUNDLE-DISPLAY-NAME]]&lt;/title&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            .icon
        ///            {
        ///                white-space:    nowrap;
        ///                text-align:     center;
        ///                vertical-align: middle;
        ///                width: 174px;
        ///            }
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///    &lt;key&gt;PayloadContent&lt;/key&gt;
        ///    &lt;dict&gt;
        ///        &lt;key&gt;URL&lt;/key&gt;
        ///        &lt;string&gt;[[PROVISIONCHECK-SERVER]][[PROVISIONCHECK-URL]]&lt;/string&gt;
        ///    &lt;key&gt;DeviceAttributes&lt;/key&gt;
        ///    &lt;array&gt;
        ///        &lt;string&gt;UDID&lt;/string&gt;
        ///        &lt;string&gt;DEVICE_NAME&lt;/string&gt;
        ///        &lt;string&gt;VERSION&lt;/string&gt;
        ///        &lt;string&gt;PRODUCT&lt;/string&gt;
        ///        &lt;stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobileconfig {
            get {
                return ResourceManager.GetString("mobileconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///        &lt;title&gt;Provisioning profile checker&lt;/title&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            .icon
        ///            {
        ///                white-space:    nowrap;
        ///                text-align:     center;
        ///                vertical-align: middle;
        ///                width: 174px;
        ///            }
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProvisioningCheck {
            get {
                return ResourceManager.GetString("ProvisioningCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///	&lt;dict&gt;
        ///		&lt;key&gt;items&lt;/key&gt;
        ///		&lt;array&gt;
        ///			&lt;dict&gt;
        ///				&lt;key&gt;assets&lt;/key&gt;
        ///				&lt;array&gt;
        ///					&lt;dict&gt;
        ///						&lt;key&gt;kind&lt;/key&gt;
        ///						&lt;string&gt;software-package&lt;/string&gt;
        ///						&lt;key&gt;url&lt;/key&gt;
        ///						&lt;string&gt;[[IPA-URL]]&lt;/string&gt;
        ///					&lt;/dict&gt;
        ///					&lt;dict&gt;
        ///						&lt;key&gt;kind&lt;/key&gt;
        ///						&lt;string&gt;display-image&lt;/string&gt;
        ///						&lt;key&gt;needs-shine&lt;/key&gt;
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
